spring:
  datasource:
    url: jdbc:h2:mem:keycrafter;MODE=mysql;
    # url: jdbc.h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
